Added option to output detailed padding info as a TSV table.

diff --git a/voropadding b/voropadding
--- a/voropadding
+++ b/voropadding
@@ -17,6 +17,7 @@ Options:
     --restriction-radius          number     for complex input, radius to be used for the restriction spheres (if any), default is 10.0
     --output-table-file           string     output table file path, default is '_stdout' to print to stdout
     --output-graphics-file        string     output file path for the PyMol drawing script, default is ''
+    --output-padding-file         string     output file path for a table of the annotated padding points table, default is ''
     --graphics-mode               string     graphics output mode, may be 'basic' or 'detailed', default is 'basic'
     --print-mode                  string     printing to stdout mode, can be 'h' or 'v', default is 'h'
     --processors                  number     maximum number of processors to run in parallel, default is 1
@@ -65,6 +66,7 @@ RESTRICTION_CENTERS=""
 RESTRICTION_RADIUS=""
 OUTPUT_TABLE_FILE="_stdout"
 OUTPUT_GRAPHICS_FILE=""
+OUTPUT_PADDING_FILE=""
 GRAPHICS_MODE="basic"
 PRINT_MODE="h"
 MAX_PROCESSORS="1"
@@ -110,6 +112,10 @@ do
 		;;
 	--output-graphics-file)
 		OUTPUT_GRAPHICS_FILE="$OPTARG"
+		shift
+		;;
+	--output-padding-file)
+		OUTPUT_PADDING_FILE="$OPTARG"
 		shift
 		;;
 	--graphics-mode)
@@ -451,12 +457,43 @@ then
 	PARAMS_FOR_BOUNDING_SPHERES="--bound-by-spheres $(cat './restriction_spheres')"
 fi
 
-cat "./inputballs" \
-| ${SCRIPTDIR}/tools/sihsolvexpand ${PARAMS_FOR_BOUNDING_SPHERES} \
-  --chain-of-interest "ligand" \
-  --max-layers "$MAX_PADDING" \
-2> /dev/null \
-> "./padded_complex"
+if [ -n "$OUTPUT_PADDING_FILE" ]
+then
+	cat "./inputballs" \
+	| ${SCRIPTDIR}/tools/sihsolvexpand ${PARAMS_FOR_BOUNDING_SPHERES} \
+	  --chain-of-interest "ligand" \
+	  --max-layers "$MAX_PADDING" \
+	  --calc-detailed-volumes \
+	2> /dev/null \
+	> "./padded_complex"
+	
+	{
+		echo "category padding_layer root_id x y z r volume"
+		
+		cat "./padded_complex" \
+		| awk '{if($1=="ligand"){print "layer" $6 " " $7 " " $2 " " $3 " " $4 " " $9 " " $8}}' \
+		| sed 's/^layer0/ligand 0/' \
+		| sed 's/^layer/padding /'
+		
+		cat "./padded_complex" \
+		| awk '{if($1=="cap"){print "cap " $6 " " $7 " " $2 " " $3 " " $4 " " $9 " 0"}}'
+	} \
+	| sed 's/\s\+/\t/g' \
+	> "./padding_table.tsv"
+	
+	if [ ! -s "padding_table.tsv" ]
+	then
+		echo >&2 "Error: failed to generate a padding table"
+		exit 1
+	fi
+else
+	cat "./inputballs" \
+	| ${SCRIPTDIR}/tools/sihsolvexpand ${PARAMS_FOR_BOUNDING_SPHERES} \
+	  --chain-of-interest "ligand" \
+	  --max-layers "$MAX_PADDING" \
+	2> /dev/null \
+	> "./padded_complex"
+fi
 
 if [ ! -s "padded_complex" ]
 then
@@ -465,6 +502,7 @@ then
 fi
 
 cat "./padded_complex" \
+| awk '{print $1 " " $2 " " $3 " " $4 " " $5}' \
 | ${SCRIPTDIR}/tools/voronota-lt ${GRAPHICS_PARAMETERS_PADDED} \
   --print-contacts-chain-level \
   --print-cells-chain-level \
@@ -519,6 +557,12 @@ echo "${CONTENT_ROW_START}  $LIGAND_ATOMS_COUNT  $MAX_PADDING  $VOLUME_FREEDOM_C
 > "./final_result.txt"
 
 cd - &> /dev/null
+
+if [ -n "$OUTPUT_PADDING_FILE" ]
+then
+	mkdir -p "$(dirname ${OUTPUT_PADDING_FILE})"
+	cp "${TMPLDIR}/padding_table.tsv" "$OUTPUT_PADDING_FILE"
+fi
 
 if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
 then
